### ISSUE TITLE
hfmt chokes on stdin

### ISSUE THREAD

**Issue by justanotherdot** [danstiner/hfmt#17]
Trying to integrate this with `neoformat` but `:Neoformat hfmt` was returning `formatters hfmt failed to run` so I looked up the args it passes and thought I'd try via CLI:

```
❯ cat src/<source file>.hs | hfmt -
hfmt: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at app/Actions.hs:23:25 in main:Actions
```

Which makes sense given [`Actions.hs:23`](https://github.com/danstiner/hfmt/blob/8ea16f4affd226e59cfdffd92c2ec21b1355df82/app/Actions.hs#L23).

and also given:

```
❯ hfmt -s src/<source file>.hs
hfmt: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at app/Actions.hs:23:25 in main:Actions
```

Is this feature currently unsupported / experimental (printing sources)? Seems to messing up stdin processing.

**Comment by danstiner** [comment]
Indeed, looks like I never got around to finishing out the implementation!

I may take a look and clean up a bit at some point, but always feel free to send a PR. I basically am shooting to re-create the behavior of gofmt/rustfmt, so whatever stdin behavior they have would be best.

**Comment by justanotherdot** [comment]
Sure thing; if I can find the time to wrap my head around everything I'll try to give it a shot. I'll leave this open until it gets fixed somehow.

**Comment by BjornMelgaard** [comment]
workaround without neoformat, in init.vim, if anyone interested

```
function! Hfmt() abort
  let path = expand('%:p')
  let format = 'hfmt -w '
  call system(format . path)
  edit!
endfunction

augroup fmt-haskell
  autocmd!
  autocmd BufWritePost *.hs call Hfmt()
augroup END
```

P.S. @andybalaam thank you for great formatter!

**Comment by danstiner** [comment]
Just uploaded 0.2.0 which should include the changes justanotherdot submitted. Please re-open if there are still any problems.
