### ISSUE TITLE
stack install hfmt fails on Windows with latest stack (stylish-haskell must match ==0.9.*)

### ISSUE THREAD

**Issue by Ciantic** [danstiner/hfmt#38]
Installing on fresh stack setup, I get following error:

```text
stack install hfmt
Writing implicit global project config file to: C:\sr\global-project\stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-11.14
Downloaded lts-11.14 build plan.

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hfmt-0.2.2:
    stylish-haskell must match ==0.9.*, but the stack configuration has no specified version
                    (latest matching version is 0.9.2.0)
needed since hfmt is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some
    working build configuration. This can be convenient when dealing with many complicated
    constraint errors, but results may be unpredictable.

  * Recommended action: try adding the following to your extra-deps
    in C:\sr\global-project\stack.yaml:

stylish-haskell-0.9.2.0@sha256:c43a964348b144c9dbe82391b27a9010a53405a8edf3db80abde0ca1d7117911

Plan construction failed.
```

To me the error message is weird, isn't 0.9.* matching with 0.9.2.0?

**Comment by Musilitar** [comment]
+1

Having the exact same issue, and also don't understand the error message unfortunately.

**Comment by Ciantic** [comment]
@Musilitar I got these weird messages subsequently a lot with other packages too. Maybe it's Windows problem. The Haskell tooling is such a mess.

However that and others can be actually fixed with the suggestion in the message:

Add `stylish-haskell-0.9.2.0@sha256:c43a964348b144c9dbe82391b27a9010a53405a8edf3db80abde0ca1d7117911`  to `extra-deps` array in `C:\sr\global-project\stack.yaml`

**Comment by Musilitar** [comment]
@Ciantic 

Thanks!
Yes I've been having some problems on Windows in general so I guess I'll switch to Linux again.
So this is probably not a problem of this package but just Stack on Windows.

**Comment by danstiner** [comment]
This is not a bug but a side effect of how stack works, since `stylish-haskell` and `hindent` are not in the stack snapshots so you'll have to manually add them to your stack.yaml as the build command suggested. I know that's annoying but unless someone maintains those packages in the stack snapshot I think that's just how it will be.

More info: https://docs.haskellstack.org/en/stable/stack_yaml_vs_cabal_package_file/

**Comment by danstiner** [comment]
To circle back on this, it isn't a linux vs Windows thing but just the way `stack` works with packages that are not part of the snapshot.

Things have gotten a bit better however, `stylish-haskell` is now part of stackage, so only `hindent` needs to be added manually.
