### ISSUE TITLE
stack update to lts-14.6 and ghc 8.6.5

### ISSUE THREAD

**Issue by ynishi** [danstiner/hfmt#49]
I built via stack today, and failed(It may be no problem to build other environment, like in docker container.).
- environment
  - Debian 9.4
  - stack 2.1.3
  - installed ghc 8.6.5

I tried to update stack.yaml and success without change app source(just reformat to pass test).
How about update?

## change
- update stack.yaml
  - update resolver to lts-14.6
  - update hindent version
  - add stylish-haskell version
- hfmt source(because stack test failed)

## diff
https://github.com/danstiner/hfmt/compare/master...ynishi:support_ghc_8.6.5?expand=1

## check
- stack build, test, install succeeded.
- `hfmt -w .` command worked.
- but no completely check all features.

**Comment by danstiner** [comment]
Thanks for the cleanup, merged to master: https://github.com/danstiner/hfmt/commit/b40725f4125d1985a269b5f50785c0a2a9ef1a52

**Comment by ynishi** [comment]
Thanks for to marge!

**Comment by danstiner** [comment]
Of course!
