### ISSUE TITLE
Basic readme

### ISSUE THREAD

**Issue by begriffs** [danstiner/hfmt#5]
Hey sorry for sending an issue rather than a PR, but some people on Twitter said they wish there was a readme that shows briefly how hfmt works. Thought I'd pass it along.

**Comment by danstiner** [comment]
Excellent idea, I'll see if I have time later this week to throw one up.

**Comment by danstiner** [comment]
A basic readme was added a few weeks ago and I just uploaded a slightly newer version to hackage.

Closing this for now, happy to expand the readme if usage is not clear
