### ISSUE TITLE
Update to latest hlint, hindent, and stylish-haskell

### ISSUE THREAD

**Issue by danstiner** [danstiner/hfmt#9]
These dependencies have some breaking API changes that need to be accommodated before the this project can build against newer versions of them.

**Comment by alx741** [comment]
Same here, doing `stack install hfmt` complains:

```
While constructing the build plan, the following exceptions were encountered:

In the dependencies for hfmt-0.0.2.3:
    stylish-haskell-0.6.1.0 must match ==0.5.* (latest applicable is 0.5.17.0)

Plan construction failed.
```

Having `hfmt` to work with `stylish-haskell-0.6.*`  would be nice

**Comment by danstiner** [comment]
Thanks for the comment, definitely would be nice to work with newer stackage versions but there were some breaking changes in stylish 0.6 that need to be accommodated before this can work. 
I'm currently traveling but I'll take a look when I get the chance.

**Comment by zkourouma** [comment]
looks like `stack install hfmt` is failing due to hindent and stylish-haskell versions. 
`hindent-5.2.3 must match >=4.5 && <5 (latest applicable is 4.6.4)`
`stylish-haskell-0.7.1.0 must match ==0.5.* (latest applicable is 0.5.17.0)`

**Comment by danstiner** [comment]
Releasing a new version now that supports building with stackage versions >= 8, thanks to you both for bumping me about this so I'd have a reason to come back and fix it.
